### ISSUE TITLE
ECCS Lab Course not showing up on ant planner

### ISSUE THREAD

**Issue by lihops** [gumho/antplanner#87]
The ECCS 12 Lab 18053, on thursday 11:00 AM to 1:50 PM doesn't show up on my calender when i click it, although it says "you have already added that course!"

**Comment by gumho** [comment]
Thanks for reporting this! I've found and fixed the problem and roll out the changes either today or tomorrow.

**Comment by lihops** [comment]
it still doesnt work for me can you try again or something?

**Comment by gumho** [comment]
ah sorry about that. it's fixed but I waited to roll the new changes until i finished another batch of changes. i'll put them up tonight for sure.

**Comment by gumho** [comment]
should be up now..

**Comment by lihops** [comment]
thanks a lot =D
